# -*- coding: utf-8 -*-
"""hybrid_87t_relay.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UaKroxsWGxQnppH-k61BuL7PLpIn_u9s
"""

"""
hybrid_87t_relay.py
====================
Robust Hybrid Differential Relay Simulator combining Adaptive 87T logic
with WT-LSTM Neural Network supervisory control.

IEC 60255-111 / IEEE C37.91 aligned differential protection model.

Version : 2.0.0
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import NamedTuple

import numpy as np

# Module-level logger — consumers configure handlers externally

logger = logging.getLogger(__name__)



# Enumerations


class TripCommand(str, Enum):
    TRIP  = "TRIP"
    BLOCK = "BLOCK"


class TripReason(str, Enum):
    INSTANTANEOUS_OC      = "Instantaneous Overcurrent Override"
    HYBRID_CONFIRMED      = "Hybrid Handshake (87T + AI Confirmed)"
    AI_VETO               = "AI Veto (Inrush / CT Saturation)"
    NO_PICKUP             = "Normal / External — No 87T Pick-up"


class Phase(int, Enum):
    A = 0
    B = 1
    C = 2



# Data containers


class PhaseResult(NamedTuple):
    """Raw per-phase evaluation output."""
    trip_87t:      bool
    instant_trip:  bool
    i_diff:        float   # differential current [p.u.]
    i_rest:        float   # restraint current [p.u.]


@dataclass(frozen=True)
class RelaySettings:
    """
    Immutable relay configuration block.

    Parameters
    ----------
    i_pickup : float
        Minimum differential pick-up current [p.u.].  Default 0.30.
    i_high_set : float
        Instantaneous (unrestrained) high-set pick-up [p.u.].  Default 10.0.
    slope_1 : float
        Percentage bias slope in the normal-load region.  Default 0.25 (25 %).
    slope_2 : float
        Percentage bias slope in the CT-saturation region.  Default 0.60 (60 %).
    breakpoint : float
        Restraint current at which slope transitions from Slope-1 to Slope-2 [p.u.].
        Default 3.0.
    ai_confidence_threshold : float
        Minimum WT-LSTM confidence score required to approve a trip.  Default 0.85.
    """
    i_pickup:               float = 0.30
    i_high_set:             float = 10.0
    slope_1:                float = 0.25
    slope_2:                float = 0.60
    breakpoint:             float = 3.0
    ai_confidence_threshold: float = 0.85

    def __post_init__(self) -> None:
        self._validate()

    def _validate(self) -> None:
        if not (0.0 < self.i_pickup < self.i_high_set):
            raise ValueError(
                f"Must satisfy 0 < i_pickup ({self.i_pickup}) "
                f"< i_high_set ({self.i_high_set})."
            )
        for name, val in (("slope_1", self.slope_1), ("slope_2", self.slope_2)):
            if not (0.0 < val < 1.0):
                raise ValueError(f"{name} must be in (0, 1); got {val}.")
        if self.slope_1 >= self.slope_2:
            raise ValueError(
                f"slope_1 ({self.slope_1}) must be less than slope_2 ({self.slope_2})."
            )
        if self.breakpoint <= 0.0:
            raise ValueError(f"breakpoint must be positive; got {self.breakpoint}.")
        if not (0.0 < self.ai_confidence_threshold <= 1.0):
            raise ValueError(
                f"ai_confidence_threshold must be in (0, 1]; "
                f"got {self.ai_confidence_threshold}."
            )


@dataclass
class RelayTelemetry:
    """
    Full telemetry snapshot returned for every evaluated sample.

    Attributes
    ----------
    final_command : TripCommand
        Relay output (TRIP or BLOCK).
    reason : TripReason
        Human-readable classification of the decision.
    phase_87t_flags : list[bool]
        Per-phase differential element pick-up status [A, B, C].
    phase_instant_flags : list[bool]
        Per-phase high-set element pick-up status [A, B, C].
    i_diff_abc : list[float]
        Differential current magnitude per phase [p.u.].
    i_rest_abc : list[float]
        Restraint current per phase [p.u.].
    lstm_confidence : float
        WT-LSTM neural network output score (0.0 – 1.0).
    ai_veto_detail : str
        Additional context when a BLOCK is issued via AI veto; empty otherwise.
    """
    final_command:       TripCommand
    reason:              TripReason
    phase_87t_flags:     list[bool]
    phase_instant_flags: list[bool]
    i_diff_abc:          list[float]
    i_rest_abc:          list[float]
    lstm_confidence:     float
    ai_veto_detail:      str = field(default="")


    # Convenience helpers

    @property
    def faulted_phases(self) -> list[str]:
        """Return names of phases with an active 87T or instantaneous flag."""
        names = [p.name for p in Phase
                 if self.phase_87t_flags[p] or self.phase_instant_flags[p]]
        return names

    @property
    def is_trip(self) -> bool:
        return self.final_command is TripCommand.TRIP

    def summary(self) -> str:
        """Single-line diagnostic string for logging / SCADA integration."""
        phases = ", ".join(self.faulted_phases) or "—"
        return (
            f"[{self.final_command.value}] {self.reason.value} | "
            f"Phases: {phases} | "
            f"Idiff={[f'{v:.3f}' for v in self.i_diff_abc]} | "
            f"Irest={[f'{v:.3f}' for v in self.i_rest_abc]} | "
            f"LSTM={self.lstm_confidence:.3f}"
        )



# Core relay class


class HybridAdaptive87TRelay:
    """
    Three-phase percentage-differential relay with dual-slope adaptive
    characteristic and WT-LSTM supervisory veto logic.

    Protection logic overview
    -------------------------
    1. **Instantaneous high-set (unrestrained)**
       Trips immediately when I_diff > I_high_set on any phase, bypassing
       all supervisory logic.

    2. **Dual-slope percentage-differential (87T)**
       - Region 1 (I_rest ≤ breakpoint): picks up when I_diff > Slope_1 × I_rest
       - Region 2 (I_rest > breakpoint): picks up when
         I_diff > Slope_2 × (I_rest − BP) + Slope_1 × BP

    3. **WT-LSTM supervisory gate**
       An 87T pick-up issues a TRIP only when the neural network confidence
       score ≥ `ai_confidence_threshold`; otherwise the event is classified
       as inrush / CT saturation and the trip is blocked.

    Parameters
    ----------
    settings : RelaySettings | None
        Relay configuration dataclass.  If ``None``, default settings are used.

    Examples
    --------
    >>> relay = HybridAdaptive87TRelay()
    >>> hv = np.array([5.0, 0.05, 0.05])
    >>> lv = np.array([0.1, 0.05, 0.05])
    >>> tel = relay.process_sample(hv, lv, lstm_confidence=0.95)
    >>> print(tel.summary())
    [TRIP] Hybrid Handshake (87T + AI Confirmed) | Phases: A | ...
    """

    NUM_PHASES: int = 3

    def __init__(self, settings: RelaySettings | None = None) -> None:
        self.settings: RelaySettings = settings or RelaySettings()
        logger.debug("Relay initialised with settings: %s", self.settings)


    # Public interface


    def process_sample(
        self,
        i_hv_abc: np.ndarray | list[complex | float],
        i_lv_abc: np.ndarray | list[complex | float],
        lstm_confidence: float,
    ) -> RelayTelemetry:
        """
        Evaluate one time-step of three-phase CT data.

        Parameters
        ----------
        i_hv_abc :
            HV-side CT-compensated phasors / magnitudes, shape (3,) [p.u.].
        i_lv_abc :
            LV-side CT-compensated phasors / magnitudes, shape (3,) [p.u.].
        lstm_confidence :
            Scalar output of the WT-LSTM classifier in [0.0, 1.0].

        Returns
        -------
        RelayTelemetry
            Full decision record including per-phase flags and telemetry.

        Raises
        ------
        ValueError
            If input arrays are not length-3 or confidence is out of range.
        """
        self._validate_inputs(i_hv_abc, i_lv_abc, lstm_confidence)

        # ---- Phase-by-phase evaluation --------------------------------
        phase_results: list[PhaseResult] = [
            self._evaluate_phase(i_hv_abc[ph], i_lv_abc[ph])
            for ph in range(self.NUM_PHASES)
        ]

        # ---- Aggregate flags ----
        trips_87t      = [r.trip_87t     for r in phase_results]
        instant_trips  = [r.instant_trip for r in phase_results]
        i_diffs        = [r.i_diff       for r in phase_results]
        i_rests        = [r.i_rest       for r in phase_results]

        any_instant    = any(instant_trips)
        any_87t        = any(trips_87t)
        ai_approves    = lstm_confidence >= self.settings.ai_confidence_threshold

        # ---- Decision tree ----------
        telemetry = self._make_decision(
            any_instant, any_87t, ai_approves,
            trips_87t, instant_trips, i_diffs, i_rests, lstm_confidence,
        )

        logger.info(telemetry.summary())
        return telemetry

    def update_settings(self, **kwargs) -> None:
        """
        Non-destructively update relay settings by replacing the frozen
        dataclass with a new instance carrying the modified values.

        Example
        -------
        >>> relay.update_settings(slope_1=0.30, ai_confidence_threshold=0.90)
        """
        current = {f: getattr(self.settings, f)
                   for f in self.settings.__dataclass_fields__}
        current.update(kwargs)
        self.settings = RelaySettings(**current)
        logger.info("Settings updated: %s", self.settings)

# Internal helpers


    def _evaluate_phase(
        self,
        i_hv: complex | float,
        i_lv: complex | float,
    ) -> PhaseResult:
        """
        Compute differential and restraint quantities and apply the
        adaptive dual-slope characteristic for a single phase.

        .. note::
            ``i_hv`` and ``i_lv`` must already be CT-ratio and vector-group
            compensated (magnitude and angle aligned) before being passed in.
        """
        s  = self.settings
        i_diff = abs(i_hv - i_lv)
        i_rest = (abs(i_hv) + abs(i_lv)) / 2.0

        instant_trip = i_diff > s.i_high_set
        trip_87t     = False

        if i_diff > s.i_pickup:
            if i_rest <= s.breakpoint:
                # ── Region 1: Normal load / light external fault ──────
                trip_87t = i_diff > (s.slope_1 * i_rest)
            else:
                # ── Region 2: Heavy CT saturation bias shift ──────────
                dynamic_bias = (
                    s.slope_2 * (i_rest - s.breakpoint)
                    + s.slope_1 * s.breakpoint
                )
                trip_87t = i_diff > dynamic_bias

        return PhaseResult(
            trip_87t=trip_87t,
            instant_trip=instant_trip,
            i_diff=i_diff,
            i_rest=i_rest,
        )

    def _make_decision(
        self,
        any_instant:    bool,
        any_87t:        bool,
        ai_approves:    bool,
        trips_87t:      list[bool],
        instant_trips:  list[bool],
        i_diffs:        list[float],
        i_rests:        list[float],
        lstm_confidence: float,
    ) -> RelayTelemetry:
        """Encapsulate the hybrid decision tree, returning a populated telemetry object."""
        s = self.settings

        if any_instant:
            command = TripCommand.TRIP
            reason  = TripReason.INSTANTANEOUS_OC
            detail  = ""

        elif any_87t and ai_approves:
            command = TripCommand.TRIP
            reason  = TripReason.HYBRID_CONFIRMED
            detail  = ""

        elif any_87t and not ai_approves:
            command = TripCommand.BLOCK
            reason  = TripReason.AI_VETO
            detail  = (
                f"LSTM={lstm_confidence:.3f} < threshold={s.ai_confidence_threshold:.3f}"
            )

        else:
            command = TripCommand.BLOCK
            reason  = TripReason.NO_PICKUP
            detail  = ""

        return RelayTelemetry(
            final_command=command,
            reason=reason,
            phase_87t_flags=trips_87t,
            phase_instant_flags=instant_trips,
            i_diff_abc=i_diffs,
            i_rest_abc=i_rests,
            lstm_confidence=lstm_confidence,
            ai_veto_detail=detail,
        )

    @staticmethod
    def _validate_inputs(
        i_hv_abc: np.ndarray | list,
        i_lv_abc: np.ndarray | list,
        lstm_confidence: float,
    ) -> None:
        if len(i_hv_abc) != 3 or len(i_lv_abc) != 3:
            raise ValueError("i_hv_abc and i_lv_abc must each have exactly 3 elements.")
        if not (0.0 <= lstm_confidence <= 1.0):
            raise ValueError(
                f"lstm_confidence must be in [0, 1]; got {lstm_confidence}."
            )

# Quick-start demo (python hybrid_87t_relay.py)


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)-8s | %(message)s",
    )

    relay = HybridAdaptive87TRelay()

    scenarios: list[tuple[str, np.ndarray, np.ndarray, float]] = [
        (
            "Internal Phase-A Fault (should TRIP)",
            np.array([5.5 + 0j, 0.05 + 0j, 0.05 + 0j]),
            np.array([0.10 + 0j, 0.05 + 0j, 0.05 + 0j]),
            0.97,
        ),
        (
            "Inrush Condition (AI vetoes)",
            np.array([2.0 + 0j, 0.05 + 0j, 0.05 + 0j]),
            np.array([0.05 + 0j, 0.05 + 0j, 0.05 + 0j]),
            0.42,
        ),
        (
            "External Fault / Normal Load (BLOCK)",
            np.array([1.0 + 0j, 1.0 + 0j, 1.0 + 0j]),
            np.array([1.0 + 0j, 1.0 + 0j, 1.0 + 0j]),
            0.10,
        ),
        (
            "Instantaneous OC override (TRIP, no AI needed)",
            np.array([12.0 + 0j, 0.05 + 0j, 0.05 + 0j]),
            np.array([0.10 + 0j, 0.05 + 0j, 0.05 + 0j]),
            0.20,
        ),
    ]

    separator = "─" * 72
    for label, hv, lv, conf in scenarios:
        tel = relay.process_sample(hv, lv, lstm_confidence=conf)
        print(f"\n{separator}")
        print(f"  Scenario : {label}")
        print(f"  Decision : {tel.final_command.value}  ({tel.reason.value})")
        if tel.ai_veto_detail:
            print(f"  AI Detail: {tel.ai_veto_detail}")
        print(f"  Phases   : {tel.faulted_phases or ['none']}")
        print(f"  Idiff    : {[f'{v:.3f}' for v in tel.i_diff_abc]}")
        print(f"  Irest    : {[f'{v:.3f}' for v in tel.i_rest_abc]}")
    print(f"\n{separator}\n")