% test_scale_factor.m
% Add a gain of 400 inside the DWT Stateflow block, compile, run simulation, and check LSTM prediction.

try
    model = 'TransformerWithCTSaturation';
    if ~bdIsLoaded(model)
        load_system(model);
    end
    
    subsys = [model '/Hybrid 87T Relay'];
    dwt = [subsys '/DWT Feature Extraction'];
    
    % Find Stateflow Chart object
    rt = sfroot;
    chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', dwt);
    if isempty(chart)
        error('DWT Feature Extraction chart not found!');
    end
    
    % Modify DWT code to multiply by 400 (referring secondary current to primary current)
    dwt_code = sprintf([ ...
        'function features = extractFeatures(I_diff_window)\n' ...
        '    %% Extract wavelet features at 1600 Hz sample rate\n' ...
        '    features = zeros(1, 9);\n' ...
        '    \n' ...
        '    for ph = 1:3\n' ...
        '        %% Multiply by 400 to refer secondary current to primary line current\n' ...
        '        signal = I_diff_window(:, ph) * 400;\n' ...
        '        \n' ...
        '        %% Pre-initialize variables for code generation compliance\n' ...
        '        C = zeros(45, 1);\n' ...
        '        L = zeros(4, 1);\n' ...
        '        d1 = zeros(19, 1);\n' ...
        '        d2 = zeros(13, 1);\n' ...
        '        a2 = zeros(13, 1);\n' ...
        '        \n' ...
        '        %% 2-level db4 wavelet decomposition\n' ...
        '        [C, L] = wavedec(signal, 2, ''db4'');\n' ...
        '        \n' ...
        '        %% Calculate squared DWT energy coefficients\n' ...
        '        d1 = detcoef(C, L, 1);\n' ...
        '        d2 = detcoef(C, L, 2);\n' ...
        '        a2 = appcoef(C, L, ''db4'', 2);\n' ...
        '        \n' ...
        '        E_D1 = sum(d1.^2);\n' ...
        '        E_D2 = sum(d2.^2);\n' ...
        '        E_A2 = sum(a2.^2);\n' ...
        '        \n' ...
        '        %% Store features in 9-element feature vector\n' ...
        '        base = (ph - 1) * 3 + 1;\n' ...
        '        features(base)     = E_D1;\n' ...
        '        features(base + 1) = E_D2;\n' ...
        '        features(base + 2) = E_A2;\n' ...
        '        \n' ...
        '        %% Apply log1p scaling (log(1 + x)) matching PyTorch training\n' ...
        '        features(base)     = log(1 + features(base));\n' ...
        '        features(base + 1) = log(1 + features(base + 1));\n' ...
        '        features(base + 2) = log(1 + features(base + 2));\n' ...
        '    end\n' ...
        'end' ...
    ]);
    chart.Script = dwt_code;
    save_system(model);
    fprintf('✓ DWT Stateflow block updated with gain of 400 and saved.\n');
    
    % Run simulation for Case 3 (Internal Fault)
    fprintf('Running simulation of Internal Fault with gain...\n');
    set_param([model '/Step3'], 'Time', '0.50');
    % Close HV and LV breakers
    hv = [model '/Three-Phase Breaker '];
    lv = [model '/Three-Phase Breaker1 '];
    set_param(hv, 'External', 'on');
    set_param(hv, 'InitialState', 'closed');
    set_param(hv, 'SwitchTimes', '[]');
    set_param(lv, 'External', 'on');
    set_param(lv, 'InitialState', 'closed');
    set_param(lv, 'SwitchTimes', '[]');
    
    % Set internal fault phase A to ground
    set_param([model '/Internal_Fault1'], ...
        'FaultA', 'on', 'FaultB', 'off', 'FaultC', 'off', 'GroundFault', 'on', ...
        'FaultResistance', '0.1');
    
    simOut = sim(model, 'StopTime', '1.0', 'ReturnWorkspaceOutputs', 'on');
    logs = simOut.get('logsout');
    feat_el = logs.get('DWT_Features');
    
    if ~isempty(feat_el)
        feat_data = feat_el.Values.Data;
        feat_time = feat_el.Values.Time;
        save('scaled_features_test.mat', 'feat_data', 'feat_time');
        fprintf('✓ Simulation done. Features shape: %s. Saved to scaled_features_test.mat.\n', mat2str(size(feat_data)));
    else
        fprintf('⚠ Failed to log features!\n');
    end
    
catch ME
    disp(['Error: ' ME.message]);
    disp(ME.getReport());
end
